TZ: Europe/Athens

mariadb:
  image_selector: v1011_image
  user: mariadb
  password: mariadb
  database: mariadb
  root_password: mariadb

network:
  tcp_port: 3306
  host_network: false

ix_volumes:
  data: /opt/tests/mnt/data

storage:
  data:
    type: ix_volume
    ix_volume_config:
      dataset_name: data
      create_host_path: true
  additional_storage: []
